name: Tackle Pathfinder CI main

on:
  push:
    branches: [ main ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -U -B test

  integration-native-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -U -B verify -Pnative -Dquarkus-profile=test

  build-jvm-container:
    name: Build and push JVM image
    runs-on: ubuntu-latest
    needs: [unit-test, integration-native-test]
    if: github.repository_owner == 'konveyor'

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Build Image for main branch with Maven
      run: |
        ./mvnw -U -B package -DskipTests \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.additional-tags=latest-jar \
          -Dquarkus.container-image.registry=${{ secrets.QUAYIO_REPO }} \
          -Dquarkus.container-image.username=${{ secrets.QUAYIO_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.QUAYIO_PASSWORD }}

  build-native-container:
    name: Build and push native image
    runs-on: ubuntu-latest
    needs: [unit-test, integration-native-test]
    if: github.repository_owner == 'konveyor'

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Build Image for main branch with Maven
      run: |
        ./mvnw -U -B package -Pnative -DskipTests \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.additional-tags=latest-native \
          -Dquarkus.container-image.registry=${{ secrets.QUAYIO_REPO }} \
          -Dquarkus.container-image.username=${{ secrets.QUAYIO_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.QUAYIO_PASSWORD }}

  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate jacoco report
        run: ./mvnw -U verify -Pjacoco
      - uses: codecov/codecov-action@v2.0.3
        with:
          file: ./target/site/jacoco/jacoco.xml
          name: codecov
